apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: devops
  labels:
    name: nexus-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.10
    path: /data/nexus
  persistentVolumeReclaimPolicy: Recycle
