apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-postgresql-pvc
  namespace: devops
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: sonarqube-postgresql-pv
