apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-conf-pv
  namespace: devops
  labels:
    name: gitlab-conf-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.10
    path: /data/gitlab/conf
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
  namespace: devops
  labels:
    name: gitlab-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.10
    path: /data/gitlab/data
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
  namespace: devops
  labels:
    name: gitlab-logs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.10
    path: /data/gitlab/logs
  persistentVolumeReclaimPolicy: Recycle

