apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry-pv
  namespace: devops
  labels:
    name: harbor-registry-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.13.128
    path: /data/harbor/registry
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-chartmuseum-pv
  namespace: devops
  labels:
    name: harbor-chartmuseum-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.13.128
    path: /data/harbor/chartmuseum
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice-pv
  namespace: devops
  labels:
    name: harbor-jobservice-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.13.128
    path: /data/harbor/jobservice
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-database-pv
  namespace: devops
  labels:
    name: harbor-database-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.13.128
    path: /data/harbor/database
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-redis-pv
  namespace: devops
  labels:
    name: harbor-redis-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.13.128
    path: /data/harbor/redis
  persistentVolumeReclaimPolicy: Retain
