expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: registry.devops.io
      notary: notary.devops.io
    annotations:
      kubernetes.io/ingress.class: "nginx"

externalURL: http://registry.devops.io

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      existingClaim: "harbor-registry-pvc"
    chartmuseum:
      existingClaim: "harbor-chartmuseum-pvc"
    jobservice:
      existingClaim: "harbor-jobservice-pvc"
    database:
      existingClaim: "harbor-database-pvc"
    redis:
      existingClaim: "harbor-redis-pvc"
