apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    name: jenkins-pv
  namespace: devops
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.10
    path: /data/jenkins_home
  persistentVolumeReclaimPolicy: Recycle
